# Generated by Django 3.2.20 on 2023-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
