# Generated by Django 3.2.20 on 2023-07-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_status',
            field=models.BooleanField(default=False, verbose_name='주문상태'),
        ),
    ]
