# Generated by Django 3.2.20 on 2023-07-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='my_order',
        ),
    ]
